name: winkill_test

on: [push]

env:
  BUILD_TYPE: Release

permissions:
  contents: read

jobs:
  compile_latest:
    runs-on: ubuntu-26.04

    steps:
      - name: install_packages
        run: |
             sudo dpkg --add-architecture i386
             sudo apt-get update
             sudo apt-get -y upgrade
             sudo apt-get install g++-mingw-w64-x86-64 cmake nsis automake rsync p7zip-full g++ gettext python3 tcl libgcc-s1:i386 libstdc++6:i386 bsdutils wget mingw-w64-tools wine
      - name: configure compiler
        run: |
             sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
             sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
      - name: checkout maxima
        run: |
             wget -O maxima-5.50.0.tar.gz https://sourceforge.net/projects/maxima/files/Maxima-source/5.50.0-source/maxima-5.50.0.tar.gz/download
             tar xvf maxima-5.50.0.tar.gz
             mkdir maxima-5.50.0/crosscompile-windows/build
             cd maxima-5.50.0/crosscompile-windows/build
             cmake ..
             make winkill VERBOSE=1
             ls -l winkill.exe
             md5sum winkill.exe
      - name: get maxima installer
        run: |
             wget -O maxima-5.50.0-win64.exe https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.50.0-Windows/maxima-5.50.0-win64.exe/download
             7z x maxima-5.50.0-win64.exe bin/winkill.exe
             ls -l bin/winkill.exe
             sha256sum bin/winkill.exe
      - name: compare compiled winkill.exe and that from the installer
        run: |
             # show the sizes of the file from the installer and the self compiled file (winkill.exe).
             ls -l bin/winkill.exe maxima-5.50.0/crosscompile-windows/build/winkill.exe
             diff bin/winkill.exe maxima-5.50.0/crosscompile-windows/build/winkill.exe || true
             # which bytes are really different?
             cmp --verbose bin/winkill.exe maxima-5.50.0/crosscompile-windows/build/winkill.exe
